#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml

from core.version_manifest import VersionManifest

DEFAULT_MANIFEST_PATH = Path("config/version_manifest.yaml")
DEFAULT_OUTPUT_PATH = Path("web/app/src/lib/generated/version-manifest.ts")


def _load_manifest(manifest_path: Path) -> VersionManifest:
    payload = yaml.safe_load(manifest_path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"Invalid manifest payload: {manifest_path}")
    return VersionManifest.model_validate(payload)


def _render_ts(manifest: VersionManifest) -> str:
    manifest_json = json.dumps(manifest.model_dump(mode="json"), indent=2, sort_keys=True)
    return (
        "// This file is generated by scripts/sync_version_manifest.py.\n"
        "// Do not edit manually.\n\n"
        f"export const VERSION_MANIFEST = {manifest_json} as const;\n\n"
        "export type VersionManifest = typeof VERSION_MANIFEST;\n\n"
        "export const SUPPORTED_SCHEMA_VERSIONS = VERSION_MANIFEST.compatibility.ui_schema.supported_versions;\n"
        "export const DEFAULT_SCHEMA_VERSION = VERSION_MANIFEST.compatibility.ui_schema.default_version;\n"
    )


def _write_or_check(output_path: Path, content: str, check: bool) -> int:
    if check:
        if not output_path.exists():
            print(f"[ERROR] Generated manifest artifact is missing: {output_path}")
            return 1
        existing = output_path.read_text(encoding="utf-8")
        if existing != content:
            print(
                "[ERROR] Generated manifest artifact is out of date.\n"
                "Run: pixi run sync-version-manifest"
            )
            return 1
        print(f"[OK] Manifest artifact is up to date: {output_path}")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print(f"[OK] Wrote manifest artifact: {output_path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate or validate web manifest artifact from config/version_manifest.yaml")
    parser.add_argument(
        "--manifest",
        type=Path,
        default=DEFAULT_MANIFEST_PATH,
        help="Path to YAML version manifest",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help="Path to generated TypeScript artifact",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate generated output without writing files",
    )
    args = parser.parse_args()

    manifest = _load_manifest(args.manifest)
    content = _render_ts(manifest)
    return _write_or_check(args.output, content, args.check)


if __name__ == "__main__":
    raise SystemExit(main())
